{ config, pkgs, lib, ... }:

let
  # Base directory for Kafka configs in WSL
  kafkaDir = "${config.home.homeDirectory}/.kafka";
  certsDir = "${kafkaDir}/certs";
in
{
  # ============================================
  # Kafka CLI Tools
  # ============================================
  home.packages = with pkgs; [
    apacheKafka  # Provides kafka-consumer-groups.sh, kafka-topics.sh, etc.
    kafkactl     # Modern CLI with context support
  ];

  # See docs/kafka-setup.md for certificate structure and setup
  home.file.".kafka/certs".source =
    config.lib.file.mkOutOfStoreSymlink "/mnt/c/Users/NikhilKrishnaNair/.kafka/certs";

  # ============================================
  # Kafka Configuration Files (generated by Nix)
  # ============================================
  # Config files with correct WSL paths for certificates

  # Staging environment config
  home.file.".kafka/staging/config.properties".text = ''
    security.protocol=SSL
    ssl.keystore.type=PEM
    ssl.keystore.location=${certsDir}/staging/keystore.pem
    ssl.truststore.type=PEM
    ssl.truststore.location=${certsDir}/staging/ca.pem
  '';

  # Live environment config
  home.file.".kafka/live/config.properties".text = ''
    security.protocol=SSL
    ssl.keystore.type=PEM
    ssl.keystore.location=${certsDir}/live/keystore.pem
    ssl.truststore.type=PEM
    ssl.truststore.location=${certsDir}/live/ca.pem
  '';

  # See docs/kafka-setup.md for kafkactl usage
  home.file.".config/kafkactl/config.yml".text = ''
    contexts:
      staging:
        brokers:
          - kafka-staging-hellofresh.aivencloud.com:23419
        tls:
          enabled: true
          ca: ${certsDir}/staging/ca.pem
          cert: ${certsDir}/staging/service.cert
          certKey: ${certsDir}/staging/service.key
      live:
        brokers:
          - kafka-live-hellofresh-live.aivencloud.com:23408
        tls:
          enabled: true
          ca: ${certsDir}/live/ca.pem
          cert: ${certsDir}/live/service.cert
          certKey: ${certsDir}/live/service.key

    current-context: live
  '';
}
