{ config, pkgs, lib, userConfig, ... }:

let
  # Base directory for Kafka configs in WSL
  kafkaDir = "${config.home.homeDirectory}/.kafka";
  certsDir = "${kafkaDir}/certs";
  windowsUserDir = "/mnt/c/Users/${userConfig.windowsUsername}";
in
{
  # ============================================
  # Kafka CLI Tools
  # ============================================
  home.packages = with pkgs; [
    apacheKafka  # Provides kafka-consumer-groups.sh, kafka-topics.sh, etc.
    kafkactl     # Modern CLI with context support
  ];

  # ============================================
  # Kafka Certificates (symlinked from Windows)
  # ============================================
  # Certificates managed on Windows side, symlinked here.
  # See docs/kafka-setup.md for Windows folder structure.
  home.file.".kafka/certs".source =
    config.lib.file.mkOutOfStoreSymlink "${windowsUserDir}/.kafka/certs";

  # ============================================
  # Kafka Configuration Files (generated by Nix)
  # ============================================
  # Config files with correct WSL paths for certificates

  # Staging environment config
  home.file.".kafka/staging/config.properties".text = ''
    security.protocol=SSL
    ssl.keystore.type=PEM
    ssl.keystore.location=${certsDir}/staging/keystore.pem
    ssl.truststore.type=PEM
    ssl.truststore.location=${certsDir}/staging/ca.pem
  '';

  # Live environment config
  home.file.".kafka/live/config.properties".text = ''
    security.protocol=SSL
    ssl.keystore.type=PEM
    ssl.keystore.location=${certsDir}/live/keystore.pem
    ssl.truststore.type=PEM
    ssl.truststore.location=${certsDir}/live/ca.pem
  '';

  # ============================================
  # kafkactl Configuration
  # ============================================
  # YAML config with named contexts for easy environment switching
  home.file.".config/kafkactl/config.yml".text = ''
    contexts:
      staging:
        brokers:
          - ${userConfig.kafka.staging.broker}
        tls:
          enabled: true
          ca: ${certsDir}/staging/ca.pem
          cert: ${certsDir}/staging/service.cert
          certKey: ${certsDir}/staging/service.key
      live:
        brokers:
          - ${userConfig.kafka.live.broker}
        tls:
          enabled: true
          ca: ${certsDir}/live/ca.pem
          cert: ${certsDir}/live/service.cert
          certKey: ${certsDir}/live/service.key

    current-context: live
  '';
}
